DROP TABLE prism_vendors;

CREATE TABLE prism_vendors (
    prism_job_id                  NUMBER,
-- Vendor Data(Primary Data)
    vendor_number                 VARCHAR2(30),
    vendor_id                     NUMBER,
--    vendor_site_id                NUMBER,
    vendor_tax_id                 VARCHAR2(30),
    vendor_name                   VARCHAR2(240),
    party_id                      NUMBER,
-- Certification(Secondary Data)
    certificate_number            VARCHAR2(20),
    certificate_jurisdiction      VARCHAR2(50),
    certificate_type              VARCHAR2(30),
    certificate_issued_date       VARCHAR2(10),
    recertification_date          VARCHAR2(10),
    certificate_expiration_date   VARCHAR2(10),
    date_established              NUMBER,
    url                           VARCHAR2(2000),
    phone                         VARCHAR2(30),
    fax                           VARCHAR2(20),
    contact_person_1_name         VARCHAR2(50),
    contact_person_1_phone        VARCHAR2(20),
    contact_person_1_email        VARCHAR2(100),
    contact_person_2_name         VARCHAR2(50),
    contact_person_2_phone        VARCHAR2(20),
    contact_person_2_email        VARCHAR2(100),
--    addresstype                   VARCHAR2(20),
--    address1                      VARCHAR2(500),
--    address2                      VARCHAR2(500),
--    district                      VARCHAR2(50),
--    county                        VARCHAR2(50),
--    city                          VARCHAR2(50),
--    state                         VARCHAR2(20),
--    zip                           VARCHAR2(20),
--    country                       VARCHAR2(20),
    race                          VARCHAR2(50),
    gender                        VARCHAR2(30),
    structure                     VARCHAR2(255),
    product_service_desc          VARCHAR2(2000),
    industry                      VARCHAR2(100),
    service_product               VARCHAR2(200),
    total_employees               NUMBER,
    minority_employees            VARCHAR2(30),
    insurance_number              VARCHAR2(30),
    insurance_exp_date            VARCHAR2(10),
    insurance_company             VARCHAR2(100),
    bus_doing_name                VARCHAR2(255),
    market_area                   VARCHAR2(100),
    unit                          VARCHAR2(100),
    major_customers               VARCHAR2(2000),
    primary_bus_activity          VARCHAR2(50),
    duns_number                   VARCHAR2(30),
    cage_number                   VARCHAR2(15),
    annual_sales_year             VARCHAR2(4),
    total_revenue                 NUMBER
---- EEO/AA
--EEO_AA_tax_id varchar2(30),
--EEO_AA_Name	varchar2(100),
--EEO_AA_Gender	varchar2(30),
--EEO_AA_ceritification varchar2(20),
--EEO_AA_Cert_Number	number,
--EEO_AA_Cert_Specialist varchar2(100),	
--EEO_AA_Cert_Expiration	varchar2(10),
--EEO_AA_Site_Visits	varchar2(20),
--EEO_AA_Workflow	varchar2(1000),
--EEO_AA_References	varchar2(1000),
--EEO_AA_Product_Service_Desc	varchar2(2000),
--EEO_AA_Status	varchar2(1000),
--EEO_AA_Phone varchar2(20),
--EEO_AA_Fax varchar2(20),
--EEO_AA_Contact_Name varchar2(1000),	
--EEO_AA_Contact_Phone varchar2(100),	
--EEO_AA_Contact_Email varchar2(100),
--EEO_AA_Address varchar2(1000),	
--EEO_AA_Address_Type	varchar2(1000),
--EEO_AA_Address_1 varchar2(1000),
--EEO_AA_Address_2 varchar2(1000),
--EEO_AA_City	varchar2(1000),
--EEO_AA_District	varchar2(50),
--EEO_AA_County	varchar2(50),
--EEO_AA_State	varchar2(2),
--EEO_AA_Zip	varchar2(10),
--EEO_AA_Country varchar2(20),
--EEO_AA_Parent_Company varchar2(1000),	
--EEO_AA_Doing_Business varchar2(255),
--EEO_AA_URL_Website_address varchar2(100),
--EEO_AA_No_of_Employees number,
--EEO_AA_Industrys varchar2(1000),	
--EEO_AA_Services varchar2(1000),	
--EEO_AA_Structure varchar2(1000),
--EEO_AA_Year_Founded	varchar2(1000),
--EEO_AA_Primary_Bus_Activity	varchar2(20),
---- Certification
--Cert_Tax_Id varchar2(20),
--Cert_Name	varchar2(100),
--Cert_Gender	varchar2(30),
--Cert varchar2(100),
--Cert_Number	varchar2(20),
--Cert_Type	varchar2(1000),
--Cert_Expiration	varchar2(10),
--Cert_Status varchar2(100),
--Cert_Owners_First_Middle_Last	varchar2(1000),
--Cert_Owners_SSN	varchar2(20),
--Cert_Owners_Equity varchar2(1000),
--Cert_Position	varchar2(1000),
--Cert_Memo varchar2(1000),
--Cert_Year varchar2(1000),
--Cert_Site_Visit	varchar2(1000),
--Cert_Start 	varchar2(10),
--Cert_End		varchar2(10),
--Cert_Findings_Comments	varchar2(1000),
--Cert_Visitor	varchar2(1000),
--Cert_Custom_Fields	varchar2(1000),
--Cert_Phone varchar2(20),
--Cert_Fax varchar2(20),
--Cert_Contract_Name	varchar2(100),
--Cert_Contact_Phone varchar2(20),
--Cert_contact_Email	varchar2(100),
--Cert_Address varchar2(1000),
--Cert_Address_Type	varchar2(1000),
--Cert_Address_1	varchar2(1000),
--Cert_Address_2	varchar2(1000),
--Cert_City	varchar2(1000),
--Cert_District	varchar2(50),
--Cert_County	varchar2(50),
--Cert_State	varchar2(2),
--Cert_Zip	varchar2(10),
--Cert_Country varchar2(20),
--Cert_Parent_Company varchar2(1000),	
--Cert_Doing_Business varchar2(255),
--Cert_URL_Website_address	varchar2(100),
--Cert_Insurance_Policy_num varchar2(1000),	
--Cert_Insurance_Expiration_Date varchar2(20),
--Cert_Insurance_Company	varchar2(100),
--Cert_No_of_Employees number,
--Cert_Industry	varchar2(1000),
--Cert_Service	varchar2(1000),
--Cert_Structure	varchar2(1000),
--Cert_Year_Founded	varchar2(1000),
--Cert_Board_Member_Name varchar2(1000),
--Cert_Size	varchar2(1000),
--Cert_Revenue varchar2(1000),
--Cert_Num_Employees	varchar2(1000),
--Cert_Complaint varchar2(1000),	
--Cert_Reference_Number	varchar2(1000),
--Cert_Assigned_to varchar2(1000),
--Cert_Assignment_Date varchar2(10),
--Cert_Determination	varchar2(1000),
--Cert_Action_Taken	varchar2(1000),
--Cert_Date_Received	varchar2(10),
--Cert_Date_Submitted	varchar2(10),
--Cert_Date_Completed	varchar2(10),
--Cert_Complainant_Address1 varchar2(1000),	
--Cert_Complainant_Address2	varchar2(1000),
--Cert_Complainant_District	varchar2(1000),
--Cert_Complainant_County	varchar2(1000),
--Cert_Complainant_City	varchar2(1000),
--Cert_Complainant_State	varchar2(1000),
--Cert_Complainant_Zip	varchar2(1000),
--Cert_Complainant_Phone	varchar2(1000),
--    CONSTRAINT pk_prism_vendors PRIMARY KEY ( prism_job_id,
--    vendor_number,
--    vendor_id)
--    ,
--    vendor_site_id )
);